locale: tr_TR
country: TR
tweet_count: 4
banned_words: ["hakaret", "küfür", "ırkçı", "nefret"]
style:
  tone: "bilgilendirici, kısa ve akıcı"
  include_hashtags: true
  max_hashtags: 2
  include_emoji: false
  include_call_to_action: false
url_policy:
  allow_links: true
  shorten_with_bitly: false
