name: BIST Returns Daily

on:
  schedule:
    # Europe/Istanbul (UTC+3) 18:30 == 15:30 UTC
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements_bist.txt; fi

      - name: Run collector
        run: |
          python scripts/bist_returns.py

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update BIST returns JSON [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
