name: Daily Turkey News Thread

on:
  schedule:
    # Her gün Türkiye saati 17:00 (UTC 14:00)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  tweet-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('bot_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot_requirements.txt
    
    - name: Run Turkey News Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MODEL: 'gpt-3.5-turbo'
        POST_TO_TWITTER: ${{ secrets.POST_TO_TWITTER }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python daily_tr.py
    
    - name: Upload tweet history
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tweet-history
        path: tweets.txt
        retention-days: 30
    
    - name: Commit tweet history (optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Eğer tweets.txt değiştiyse commit et
        if [ -n "$(git status --porcelain tweets.txt)" ]; then
          git add tweets.txt
          git commit -m "Tweet history updated: $(date +'%Y-%m-%d %H:%M')"
          git push
        fi
      continue-on-error: true
