name: trend-tweets

on:
  schedule:
    # TSİ 18:30 (Türkiye UTC+3) -> GitHub Actions cron UTC 15:30
    - cron: "30 15 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: trend-tweets
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # BIST Analiz Botu: --post ile gerçek gönderim
      - name: Run BIST Analysis and Post Tweet
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OWNER_HANDLE: "@durbirbakiyim"
          # İsteğe bağlı, kodunuz kullanıyorsa:
          # X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          # TWEET_TEXT: ${{ secrets.TWEET_TEXT }}
        run: |
          python src/main.py --post
