name: trend-tweets

on:
schedule:
# TSİ 18:30'a denk gelir (UTC 15:30).
# Hafta içi her gün (Pazartesi=1, Cuma=5) çalışır.
- cron: "30 15 * * 1-5"
workflow_dispatch:

jobs:
run:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4

  - uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - run: pip install -r requirements.txt

  # BIST Analiz Botu: Açıkça --post argümanı ile çalıştırılarak
  # Dry-Run modunun devre dışı bırakılması ve tweet'in gönderilmesi sağlanır.
  - name: Run BIST Analysis and Post Tweet
    env:
      X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWEET_TEXT: ${{ secrets.TWEET_TEXT }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    run: python src/main.py --post
